trigger: none

pool:
  vmImage: ubuntu-22.04

variables:
  aws.rolecredential.maxduration: '3600'
  SNYK_ORG: 'your-snyk-organization-id'
  SNYK_PROJECT_NAME: 'your-snyk-project-name'
  SNYK_API: 'https://api.au.snyk.io/'

stages:
- stage: SASTIaC
  dependsOn: []
  jobs:
  - job: TerraformSAST
    steps:
    - script: |
        pip3 install checkov
      name: CheckovInstall
    - script: |
        checkov --quiet -d terraform --download-external-modules true
        checkov --quiet --output junitxml -d terraform --download-external-modules true > checkov-results.xml
      name: CheckovRun
    - task: PublishTestResults@2
      displayName: "Checkov Results"
      condition: succeededOrFailed()
      inputs:
        testResultsFormat: "JUnit"
        testResultsFiles: "**/checkov-*.xml"
        searchFolder: "$(Build.SourcesDirectory)"
        mergeTestResults: false
        testRuntitle: 'SOAR API Checkov - "$(System.PullRequest.SourceCommitId)"'
        failTaskOnFailedTests: false
        publishRunAttachments: true

############ Example not using the auto-PR feature, but manually running Snyk as part of CICD ##################################
# If you enable monitor, it will send the results to Snyk and create a project for artefact.
# You can then view the results in the Snyk UI and set up alerts, etc. If you don't enable monitor, it will just run the test and fail the pipeline if there are issues above the specified threshold.
# New snyk project is created for each unique project name, so you can use the same project name for all pipelines or use different project names for different pipelines. 
# If you use the same project name, it will aggregate the results in the Snyk UI. If you use different project names, it will create separate projects in the Snyk UI.
# If you have SCM integration, not needed and just can scan without monitor.
- stage: SASTCode
  dependsOn: []
  jobs:
  - job: Dependency_Scanning
    steps:
    - task: SnykSecurityScan@1
      inputs:
        serviceConnectionEndpoint: ''
        testType: 'app'
        severityThreshold: 'medium'
        failOnIssues: true
        projectName: $(SNYK_PROJECT_NAME)
        organization: '$(SNYK_ORG)'
        failOnThreshold: 'medium' #optional, depending on policy
      env:
        SNYK_API: '$(SNYK_API)'
  
  - job: Code_Scanning
    steps:
    - task: SnykSecurityScan@1
      inputs:
        serviceConnectionEndpoint: ''
        testType: 'code'
        codeSeverityThreshold: 'medium'
        failOnThreshold: 'medium'
        failOnIssues: true
        projectName: $(SNYK_PROJECT_NAME)
        organization: '$(SNYK_ORG)'
      env:
        SNYK_API: '$(SNYK_API)'

# Will scan without monitor and just post results to pipeline.
- stage: DockerSecCheck
  jobs:
  - job: DockerContainerScan
    steps:
    - script: |
        docker build -f Dockerfile -t testing:latest .
      workingDirectory: $(Build.SourcesDirectory)
      name: builddocker
    - task: SnykSecurityScan@1
      inputs:
        serviceConnectionEndpoint: 'snyktest'
        testType: 'container'
        dockerImageName: 'testing:latest'
        severityThreshold: 'medium'
        monitorWhen: 'always'
        failOnIssues: false
        failOnThreshold: 'medium'
        organization: '$(SNYK_ORG)'
      env:
        SNYK_API: '$(SNYK_API)'


- stage: Terraform
  dependsOn: []
  jobs:
  - job: TerraformCI
    displayName: Terraform CI
    steps:
    - task: AWSShellScript@1
      displayName: "Terraform Plan"
      inputs:
        awsCredentials: "weshealth-seclog"
        regionName: "ap-southeast-2"
        scriptType: inline
        disableAutoCwd: true
        inlineScript: |
          terraform init
          terraform validate
          terraform plan
        workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
