name: CD

on:
  release:
    types: [published]

env:
  AWS_REGION: ap-southeast-2

jobs:

  call-terraform-apply-prod:
    name: Call Terraform Apply
    uses: ./.github/workflows/tfapply.yaml
    with:
      environment: prod
    secrets: inherit
